---
title: "Example GxE Prediction"
output: html_notebook
---

## Introduction

Use data and instructions from (Cueves et al. 2017)[http://www.g3journal.org/content/7/1/41] to fit GxE prediction using the `BGLR`, `MTM`, and `EMMREML` packages.

```{r}

library(tidyverse)
library(EMMREML)
library(BGLR)
library(MTM)

```




## MTM Example

```{r}

### Example for fitting multi-environment model (3)

### Require MTM package (de los Campos and Grüneberg, 2016)

##### Require BGLR package (de los Campos and Pérez-Rodríguez, 2014)

##### Requiere function CV2 (López-Cruz et al., 2015)

###Data

data(wheat)

X <- wheat.X
Y <- wheat.Y

X <- scale(X,center=TRUE,scale=TRUE)
Y <- scale(Y,center=TRUE,scale=TRUE)

env <- c(1,2,3,4)
y <- Y[,env]

G <- tcrossprod(X) / ncol(X)

In <- diag(1, nrow(Y), nrow(Y))

set.seed(12345)

# Missing data
yNA <- Y
yNA[replicate(4, as.logical(rbinom(n = nrow(Y), size = 1, prob = 0.3)))] <- NA 


### Fit model (3) with MTM (see de los Campos and Grüneberg, 2016)

fm <- MTM(Y = yNA, K = list(
  list( K = G, COV = list( type = "UN", df0 = 4, S0 = diag(4) ) ),
  list( K = In, COV = list(type = "UN", df0 = 4, S0 = diag(4)) ) ),
  
  resCov = list(type = "DIAG", S0 = rep(1, 4), df0 = rep(1, 4)),
  
  nIter = 100, burnIn = 10, thin = 5, saveAt = "ext1")


# Prediction accuracy
YHatInt <- fm$YHat

test<-is.na(yNA)

tst1 <- test[,1]
tst2 <- test[,2]
tst3 <- test[,3]
tst4 <- test[,4]

COR.PT1<-cor(YHatInt[tst1,1],y[tst1,1])

COR.PT2<-cor(YHatInt[tst2,2],y[tst2,2])

COR.PT3<-cor(YHatInt[tst3,3],y[tst3,3])

COR.PT4<-cor(YHatInt[tst4,4],y[tst4,4])


```

