---
title: "S2 MET Graphics"
output: html_notebook
---

## Introduction

This is a notebook of descriptive figures and graphics for the S2 MET project.

```{r}

# Packages
library(tidyverse)
library(maps)
library(mapdata)
library(ggmap)
library(broom)
library(stringr)


# Directories
proj_dir <- "C:/Users/Jeff/Google Drive/Barley Lab/Projects/S2MET/"

# Read in the trial information
info_file <- file.path(proj_dir, "trial_metadata.csv")
trial_info <- read_csv(file = info_file)

```


## Gantt Chart

This is a chart outlining the various project goals and objectives and their expected completion




## Collaborator Map

The below map shows the locations of the the trials

```{r trial.map}

# Summarize the trial data by number of years
trial_info_summ <- trial_info %>% 
  group_by(Location) %>% 
  summarize(long = Longitude[1], lat = Latitude[1], 
            n_year = n_distinct(Year))

# Load USDA data
nass_file <- "C:/Users/Jeff/Google Drive/Barley Lab/Other/Acreage Data/USDA-NASS/USDA_NASS_2016_barley_planted_county.csv"
nass_data <- read_csv(file = nass_file)

# Filter the NASS data
nass_data1 <- nass_data %>% 
  select(State, County, Value) %>%
  mutate_at(vars(State, County), str_to_lower) %>%
  filter(County != "other (combined) counties")

# Download map data for US by county
usa_county <- map_data(map = "county")
# Download state data
usa_state <- map_data(map = "state")
# Grab data for the world
world <- map_data(map = "world")

# Adjust the groups in the states
usa_state <- usa_state %>%
  mutate(group = group + max(world$group))

# Adjust the groups in the counties
usa_county <- usa_county %>%
  mutate(group = group + max(usa_state$group))

# Remove USA
world <- world %>%
  filter(region != "USA")

# Tidy and combine
world1 <- bind_rows(usa_state, usa_county, world)

# Add the barley data to the county data
world_nass <- full_join(x = world1, y = nass_data1, by = c("region" = "State", "subregion" = "County"))

# Map
g <- ggplot(data = world_nass, aes(x = long, y = lat, group = group)) +
  geom_polygon(aes(fill = Value / 1000), color = NA) +
  geom_polygon(data = usa_state, aes(x = long, y = lat, group = group), fill = NA, color = "white") +
  geom_point(data = trial_info_summ, aes(x = long, y = lat, group = Location, size = 1)) +
  coord_fixed(ratio = 1.5, xlim = c(-125, -65), ylim = c(35, 50)) +
  scale_fill_continuous(low = "lightgreen", high = "darkgreen", na.value = "grey", 
                        name = "2016 Planted\nBarley Acres\n(thousand)") +
  scale_size_continuous(name = "Project Site", labels = "", range = c(2)) + 
  xlab("Longitude") +
  ylab("Latitude") +
  theme(
    panel.background = element_blank(),
    legend.title = element_text(size = 8),
    legend.text = element_text(size = 8),
    legend.position = "bottom")

ggsave(filename = "sites_and_barley_acreage.jpg", plot = g, width = 4, height = 2.667, dpi = 500)

```


Leaflet version

```{r leaflet}

library(leaflet)

leaflet() %>%
  addTiles() %>%
  addCircleMarkers(data = trial_info_summ, lng = ~long, lat = ~lat, radius = ~n_year, color = ~n_year)


```


## Gantt Chart for Progress

```{r gantt}

library(DiagrammeR)



```

